### ISSUE TITLE
Compatibilité des fichiers d'export JSON 

### ISSUE THREAD

**Issue by vincentj10** [LAEQ/vifeco-tools#1]
Salut David,
Pour faire suite à notre discussion de ce matin. Ci-joint deux fichiers d'export de comptage JSON identiques, l'un créé avec Vifeco 2.0 et l'autre avec Vifeco 3.0.
J'ai essayé de calculer des concordances avec matcher.py et matcher_report.py.
Voici le message d'erreur que j'obtiens :

Traceback (most recent call last):
  File "matcher.py", line 70, in <module>
    json_2 = parseFile(file2, file1)
  File "C:\Users\jarryv\Desktop\TestJSON\vifeco-tools-main\utils\reconcile.py", line 36, in parseFile
    category_set = source_json['collection']['categorySet']
KeyError: 'categorySet'

Ceci étant dit, je ne pense pas que ça vaille la peine de passer du temps à trouver une solution, car il s'agit d'une situation hypothétique pour l'instant.

Et dans tous les cas, si on s'assure de toujours conserver une copie de la base de données Vifeco, en plus des fichiers JSON, le problème ne surviendra pas, car ton script migrate_db.py permet de passer d'une version de db à l'autre.

[json_export.zip](https://github.com/LAEQ/vifeco-tools/files/6466962/json_export.zip)

**Comment by davidmaignan** [comment]
Il se peut qu'en mettant à jour les clés dans une des json cela puisse fonctionner.
